{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {
    "colab_type": "text",
    "id": "K0MV4Mx9dRQV"
   },
   "source": [
    "# Workshop on Tensorflow\n",
    "<img src = \"https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg\" align = \"center\">\n",
    "\n",
    "\n",
    "## Importing dependencies\n",
    "\n",
    "1. [Tensorflow](https://www.tensorflow.org/)\n",
    "2. [Numpy](https://www.numpy.org/)\n",
    "3. [Matplotlib](https://matplotlib.org)\n",
    "4. [OS](https://docs.python.org/3/library/os.html)\n",
    "5. [Pandas](https://pandas.pydata.org/)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 52
    },
    "colab_type": "code",
    "id": "tSaVXoWmlQxh",
    "outputId": "cca775c6-16aa-4a76-d666-1908495065e5"
   },
   "outputs": [
    {
     "ename": "ImportError",
     "evalue": "Traceback (most recent call last):\n  File \"/home/vaibagga/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py\", line 58, in <module>\n    from tensorflow.python.pywrap_tensorflow_internal import *\n  File \"/home/vaibagga/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py\", line 28, in <module>\n    _pywrap_tensorflow_internal = swig_import_helper()\n  File \"/home/vaibagga/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n  File \"/home/vaibagga/.conda/envs/tensorflow/lib/python3.5/imp.py\", line 243, in load_module\n    return load_dynamic(name, filename, file)\n  File \"/home/vaibagga/.conda/envs/tensorflow/lib/python3.5/imp.py\", line 343, in load_dynamic\n    return _load(spec)\nImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory\n\n\nFailed to load the native TensorFlow runtime.\n\nSee https://www.tensorflow.org/install/errors\n\nfor some common reasons and solutions.  Include the entire stack trace\nabove this error message when asking for help.",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "\u001b[0;32m~/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     57\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 58\u001b[0;31m   \u001b[0;32mfrom\u001b[0m \u001b[0mtensorflow\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpython\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpywrap_tensorflow_internal\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0;34m*\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     59\u001b[0m   \u001b[0;32mfrom\u001b[0m \u001b[0mtensorflow\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpython\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpywrap_tensorflow_internal\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0m__version__\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     27\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0m_mod\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 28\u001b[0;31m     \u001b[0m_pywrap_tensorflow_internal\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mswig_import_helper\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     29\u001b[0m     \u001b[0;32mdel\u001b[0m \u001b[0mswig_import_helper\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py\u001b[0m in \u001b[0;36mswig_import_helper\u001b[0;34m()\u001b[0m\n\u001b[1;32m     23\u001b[0m             \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 24\u001b[0;31m                 \u001b[0m_mod\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mimp\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mload_module\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'_pywrap_tensorflow_internal'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfp\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mpathname\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdescription\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     25\u001b[0m             \u001b[0;32mfinally\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.conda/envs/tensorflow/lib/python3.5/imp.py\u001b[0m in \u001b[0;36mload_module\u001b[0;34m(name, file, filename, details)\u001b[0m\n\u001b[1;32m    242\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 243\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0mload_dynamic\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfilename\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfile\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    244\u001b[0m     \u001b[0;32melif\u001b[0m \u001b[0mtype_\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0mPKG_DIRECTORY\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.conda/envs/tensorflow/lib/python3.5/imp.py\u001b[0m in \u001b[0;36mload_dynamic\u001b[0;34m(name, path, file)\u001b[0m\n\u001b[1;32m    342\u001b[0m             name=name, loader=loader, origin=path)\n\u001b[0;32m--> 343\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0m_load\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mspec\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    344\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mImportError\u001b[0m: libcublas.so.10.0: cannot open shared object file: No such file or directory",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-1-47f6c3981fc8>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32mimport\u001b[0m \u001b[0mtensorflow\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mtf\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mnumpy\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mnp\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mmatplotlib\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mpyplot\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mplt\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mos\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0mos\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0menviron\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'TF_CPP_MIN_LOG_LEVEL'\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m'2'\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/__init__.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     22\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     23\u001b[0m \u001b[0;31m# pylint: disable=g-bad-import-order\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 24\u001b[0;31m \u001b[0;32mfrom\u001b[0m \u001b[0mtensorflow\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpython\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mpywrap_tensorflow\u001b[0m  \u001b[0;31m# pylint: disable=unused-import\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     25\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     26\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mtensorflow\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_api\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mv1\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mapp\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/__init__.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     47\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mnumpy\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mnp\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     48\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 49\u001b[0;31m \u001b[0;32mfrom\u001b[0m \u001b[0mtensorflow\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpython\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mpywrap_tensorflow\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     50\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     51\u001b[0m \u001b[0;31m# Protocol buffers\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     72\u001b[0m \u001b[0;32mfor\u001b[0m \u001b[0msome\u001b[0m \u001b[0mcommon\u001b[0m \u001b[0mreasons\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0msolutions\u001b[0m\u001b[0;34m.\u001b[0m  \u001b[0mInclude\u001b[0m \u001b[0mthe\u001b[0m \u001b[0mentire\u001b[0m \u001b[0mstack\u001b[0m \u001b[0mtrace\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     73\u001b[0m above this error message when asking for help.\"\"\" % traceback.format_exc()\n\u001b[0;32m---> 74\u001b[0;31m   \u001b[0;32mraise\u001b[0m \u001b[0mImportError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmsg\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     75\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     76\u001b[0m \u001b[0;31m# pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mImportError\u001b[0m: Traceback (most recent call last):\n  File \"/home/vaibagga/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py\", line 58, in <module>\n    from tensorflow.python.pywrap_tensorflow_internal import *\n  File \"/home/vaibagga/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py\", line 28, in <module>\n    _pywrap_tensorflow_internal = swig_import_helper()\n  File \"/home/vaibagga/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py\", line 24, in swig_import_helper\n    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)\n  File \"/home/vaibagga/.conda/envs/tensorflow/lib/python3.5/imp.py\", line 243, in load_module\n    return load_dynamic(name, filename, file)\n  File \"/home/vaibagga/.conda/envs/tensorflow/lib/python3.5/imp.py\", line 343, in load_dynamic\n    return _load(spec)\nImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory\n\n\nFailed to load the native TensorFlow runtime.\n\nSee https://www.tensorflow.org/install/errors\n\nfor some common reasons and solutions.  Include the entire stack trace\nabove this error message when asking for help."
     ]
    }
   ],
   "source": [
    "import tensorflow as tf\n",
    "import numpy as np\n",
    "from matplotlib import pyplot as plt\n",
    "import os\n",
    "os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'\n",
    "import pandas as pd\n",
    "%matplotlib inline\n",
    "\n",
    "print(\"Tensorflow version =\",tf.__version__)\n",
    "print(tf.test.is_gpu_available())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 34
    },
    "colab_type": "code",
    "id": "BPRokb3Ylvn5",
    "outputId": "1afa55b2-9888-4871-d5e5-28a0c4f114f9"
   },
   "outputs": [],
   "source": [
    "## constant variables 0 dimensional\n",
    "x = tf.constant(2.0)\n",
    "y = tf.constant(3.0)\n",
    "\n",
    "## basic addition operation\n",
    "z = x + y\n",
    "\n",
    "## creating tensorflow session\n",
    "sess = tf.Session()\n",
    "\n",
    "## running the tensorflow session\n",
    "print(sess.run(z))\n",
    "\n",
    "## closing session\n",
    "sess.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 34
    },
    "colab_type": "code",
    "id": "uBo-BFiYmv2o",
    "outputId": "9904b64f-3eb3-42dc-91dd-a2d63d11e97d"
   },
   "outputs": [],
   "source": [
    "## vector of integers\n",
    "z_arr = tf.constant([1,2,3,4])\n",
    "\n",
    "sess = tf.Session()\n",
    "print(sess.run(z_arr))\n",
    "sess.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "metadata": {
    "colab": {},
    "colab_type": "code",
    "id": "PBE5FCV4m6CB"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(50, 1)\n",
      "(50, 1)\n"
     ]
    }
   ],
   "source": [
    "inp = 50 * np.random.rand(50, 1)\n",
    "out = 1.24 * inp + 21.23 + 6 * np.random.rand(50, 1)\n",
    "print(inp.shape)\n",
    "print(out.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 53,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 89
    },
    "colab_type": "code",
    "id": "rFDcT0GknJbU",
    "outputId": "e26ce01e-3fc6-42cb-be14-12fac9bb6e0e"
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<matplotlib.text.Text at 0x7f45cc785080>"
      ]
     },
     "execution_count": 53,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAYIAAAEKCAYAAAAfGVI8AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAF+dJREFUeJzt3X+s3fV93/HnG3MJ16TKNcmtBZd6TirLNIFhr1dRNiINcIrJSoNFWyuV0nkTqv+ZMlZtTk01lW5SB5Krqf1jq2Sl2Ty1TeMSMCiVQl1D1DWaWK5jMpKCRZfaJDf+FcBZA1dwbd7743yPub4+v+6553t+fZ8PCd1zvuecez9fS5zX9/v58f5EZiJJqq6rBt0ASdJgGQSSVHEGgSRVnEEgSRVnEEhSxRkEklRxBoEkVZxBIEkVZxBIUsVdPegGdOIDH/hAbty4cdDNkKSRcvTo0R9m5nS7941EEGzcuJG5ublBN0OSRkpEnOzkfXYNSVLFGQSSVHEGgSRVnEEgSRVnEEhSxY3ErCFJGieHjs2z7+nj/OD8AjdOTbJn+2Z2bJ0ZWHsMAknqo0PH5nno8RdYWLwIwPz5BR56/AWAS2HQ76Cwa0iS+mjf08cvhUDdwuJF9j19HHg3KObPL5C8GxSHjs2X1iaDQJL66AfnF1oebxcUZTAIJKmPbpyabHm8XVCUwSCQpD7as30zkxNrLjs2ObGGPds3A+2DogwGgST10Y6tMzxy/63MTE0SwMzUJI/cf+ulweB2QVEGZw1J0iqtdJbPjq0zTV+vH+/nrCGDQJJWoZPpoCvVKijKYNeQJK3CIGb59JpBIEmrMIhZPr1mEEjSKgxilk+vGQSStAqNZvkAvPn2hVJXA/eSQSBJq1CfDjo1OXHZ8dffXCy9NESvGASStEo7ts5w3XuunIQ5KoPGBoEk9cAoDxobBJLUA6M8aFxqEETEr0fEdyLi2xHxxYi4NiKuj4jDEfFy8XNdmW2QpH4YRGmIXiktCCJiBvjXwGxm3gKsAT4N7AWOZOYm4EjxXJJGWrsaQsOs7BITVwOTEbEIrAV+ADwE3FG8fgD4GvAbJbdDkkrX79IQvVJaEGTmfET8LvAKsAD8RWb+RUSsz8xTxdtOA+vLaoMkLTVsewUPizK7htYB9wEfBG4ErouIzyx9T2YmkE0+vzsi5iJi7ty5c2U1U1JFDGILyFFR5mDxJ4C/y8xzmbkIPA78E+BMRNwAUPw82+jDmbk/M2czc3Z6errEZkqqgnEoDleWMoPgFeBjEbE2IgLYBrwIPAXsKt6zC3iyxDZIEjDa8/zLVuYYwXMR8RjwTeACcAzYD7wXOBgRDwAngZ1ltUGS6m6cmmS+wZf+KMzzL1up6wgy8+HMvDkzb8nMX83MtzLz1czclpmbMvMTmflamW2QJBjtef5lc4cySZUwiC0gR4VBIKkyRnWef9msNSRJFWcQSFLF2TUkaeS4Qri3DAJJI6W+Qri+OKy+QhgwDLpkEEgaKa1WCLcLAu8kGjMIJI2UblcIeyfRnIPFkkZKtzuBWWuoOYNA0kjpdoWwtYaaMwgkjZRudwJrdseQwO2PPlPpctSOEUgaOd2sEN6zffNlYwRLVX28wDsCSZWw9E6ikSqPFxgEkipjx9YZvr73LqLJ61UdLzAIJFVOtzOPxpVBIKly3Jvgcg4WSxoK/Vz1694ElzMIJA3cIFb9ujfBu+wakjRwrvodLO8IJJWuXbdPs9k68+cXuP3RZ+y+KZl3BJJKVe/2mT+/QPJut8/SlbzNZutE8f5mn1NvGASSStVJt0+jWTxBrfxDq8+pNwwCSaXqpNhbo/pBy0Og3e9T90obI4iIzcCXlhz6EPBbwP8ojm8ETgA7M/P1stohabBunJpkvsGX9/LuoOWzeG5/9JmOPqfVK+2OIDOPZ+aWzNwC/CzwJvAEsBc4kpmbgCPFc0lj6s6bp1d0vM5FX/3Tr66hbcD/zcyTwH3AgeL4AWBHn9ogaQCefencio7XdVtuWivXr+mjnwa+WDxen5mnisengfWNPhARu4HdABs2bCi9gZLKsZoNYVz01R+l3xFExDXAp4A/W/5aZiZXTgyov7Y/M2czc3Z6uvUtpKThZYG34dePrqFPAt/MzDPF8zMRcQNA8fNsH9ogaUDs6x9+/QiCX+HdbiGAp4BdxeNdwJN9aIOkAbGvf/hFrXempF8ecR3wCvChzPxRcez9wEFgA3CS2vTR11r9ntnZ2ZybmyutnZI0jiLiaGbOtntfqYPFmfkG8P5lx16lNotI0ohrVUOon2WltToWnZPUlValo4G+l5VW9wwCSV1pV0Oo2WsGwfAxCCR1pZv1AdYJGk4WnZPUlVbrA6bWTjR8rdlxDZZBIKkrrdYHNJuMWOIkRa2CQSCpK63WB/xoYbHhZ5od12A5RiBVxGqmczb7bLNaQJ2WntZw8I5AqoBOtovs5WctKzFavCOQxkyjq/dWUz3b3RV089n6cReUjQaDQBojzRZ5Lf8ir+tkOme3ZaQtIT067BqSxkizq/c1EQ3f30mfvWWkx59BII2BQ8fmm+7xC3Axs+s+e/v7x59BII24pYO5zdSndnZTCtoy0uPPMQJpxDXqDlqqfvW+mj57+/vHm0EgjbhWg7YzztZRBwwCaci1WwjWbPHWzNQkX997Vz+bqhFlEEhDZukX//smJ3jj7QssXqwV6WlU13/P9s1XTBF1MFcrYRBIQ2T5OoDzDWrzLF/MtZLFW+4apkYMAmmItBv4rVs+LtDJYG6rHcUMg2pz+qg0RDrduKWbxVztdhRTdRkE0hDp5Au+2/7/bktFaPwZBNIQabSKd6k1EV0v5rJUhJopNQgiYioiHouIlyLixYj4xxFxfUQcjoiXi5/rymyDNErqq3ibeSez6/58S0WombLvCH4f+Gpm3gzcBrwI7AWOZOYm4EjxXFJhx9YZZkq4erdUhJqJLGkT0Yh4H/A88KFc8kci4jhwR2aeiogbgK9lZstLktnZ2ZybmyulndIwWj7DB2pX735xayUi4mhmzrZ7X5nTRz8InAP+W0TcBhwFHgTWZ+ap4j2ngfUltkEaSW7son4qMwiuBv4R8NnMfC4ifp9l3UCZmRHR8JYkInYDuwE2bNhQYjOl4WShN/VLmWME3we+n5nPFc8foxYMZ4ouIYqfZxt9ODP3Z+ZsZs5OT0+X2ExJqrbSgiAzTwPfi4h6//824G+Ap4BdxbFdwJNltUGS1F7ZJSY+C/xxRFwDfBf4l9TC52BEPACcBHaW3AZJUgulBkFmPg80GrHeVubflYZJrwq9WTBOZbHonFSiXhV6s2CcymSJCalEvSr0ZsE4lck7AqlD3XTN9KrQmwXjVCaDQOpAp10zy8PifZMTDTeXWWmpiGbbUVowTr1g15DUgU66ZuphMX9+gaQWFm+8fYGJq+Kyz3VT6M2CcSqTdwRSBzrpmmkUFosXk3VrJ1h7zdWrmu1jyQmVySCQlmk0FtBJ10yzsDj/5iLHfuvuVbfLkhMqi11D0hKNunceevwF7rx5um3XjBu/aFQZBNISzcYCnn3pXNta/vbja1TZNSQt0WosoJOumWsnrroUJFOTE/z2pz5id46GnncE0hLddu/Uu5Ref/PdqaJvXXinp22TytI2CCLis+4rrCo4dGyeN966cMXxTrp3XPmrUdbJHcF64BsRcTAi7omIaPsJacTUr+iXL/5at3aio+0hXfmrUdY2CDLz3wObgD8E/gXwckT8p4j46ZLbJvVNoyt6gLXXXN1RH78zhjTKOhosLraUPE1tj+ELwDrgsYg4nJmfK7OBUhmWrxVotEYArryib1ZvaM/2zQ03m3fGkEZB2yCIiAeBfw78EPg8sCczFyPiKuBlwCDQSGlUNyiARptnL72i76TekCt/NYo6uSO4Hrg/M08uPZiZ70TEveU0SypPo26ghCvCYPkVfasB4frUUr/4NYraBkFmPtzitRd72xypfM0GcJPaQrFmV/QOCGtcuaBMldNsTGBmapKv771rxZ9zQFijzgVlqpxuS0FYQkLjyjsCVU63A7sOCGtcRWajuRLDZXZ2Nufm5gbdDEkaKRFxNDNn273PriFJqrhSu4Yi4gTw98BF4EJmzkbE9cCXgI3ACWBnZr5eZjskSc31447gzszcsuT2ZC9wJDM3AUeK55KkARlE19B9wIHi8QFgxwDaIEkqlB0ECfxlRByNiN3FsfWZeap4fJpadVNJ0oCUPX3045k5HxE/CRyOiJeWvlgUs2s4bakIjt0AGzZsKLmZGmbNCr1J6o1S7wgyc774eRZ4AvgocCYibgAofp5t8tn9mTmbmbPT09NlNlNDrNlm8oeOzQ+6adLYKC0IIuK6iPiJ+mPgbuDbwFPAruJtu4Any2qDRp87f0nlK7NraD3wRLGh2dXAn2TmVyPiG8DBiHgAOAnsLLENGnEWepPKV1oQZOZ3gdsaHH8V2FbW39V4aVfozfEDafVcWayh1qrQm+MHUm8YBBpqO7bO8Mj9tzIzNUlQKxVd30ze8QOpN6w+qqHXbOcvxw+k3vCOQCOr2YYwbhQjrYxBoJHlRjFSb9g1pJHlRjFSbxgEGmnNxg8kdc6uIUmqOO8INBDtFoK5UEzqH4NAfVdfCFZfA1BfCAa1rp52r0vqLbuG1HftFoK5UEzqL4NAfdduIZgLxaT+smtIXeu2H79dIbl2r0vqLe8I1JXVFHxrtxDMhWJSfxkE6spK+vEPHZvn9kef4YN7/5zbH30GoGkhOWhdaE5S79k1pK502o/fbAbQI/ffytf33tX097tQTOof7wjUlWb99e+bnLjsuTOApOFnEKgre7ZvZuKquOL4G29fuGycwBlA0vAzCNSVHVtneO+1V/YsLl7My672LRUtDT+DQF07/+Ziw+NLr/adASQNP4NAXevkat8ZQNLwc9aQurZn++bLZgRB46t9ZwBJw80gUNfcGEYaD6UHQUSsAeaA+cy8NyKuB74EbAROADsz8/Wy26FyeLUvjb5+jBE8CLy45Ple4EhmbgKOFM8lSQNSahBExE3AzwOfX3L4PuBA8fgAsKPMNkiSWiv7juD3gM8B7yw5tj4zTxWPTwPrS26DJKmF0oIgIu4Fzmbm0WbvycwEssnnd0fEXETMnTt3rqxmSlLllXlHcDvwqYg4AfwpcFdE/BFwJiJuACh+nm304czcn5mzmTk7PT1dYjMlqdpKC4LMfCgzb8rMjcCngWcy8zPAU8Cu4m27gCfLaoNqlpeB7mTPAEnVMYh1BI8CByPiAeAksHMAbagMN4KX1E5fSkxk5tcy897i8auZuS0zN2XmJzLztX60oaosAy2pHVcWj7l2ZaAPHZvnt5/6DucXagXk1q2d4OFf+Ih3C1KFWHRuzLUqDHfo2Dx7/uxbl0IA4PU3F9nz2LccR5AqxCAYc63KQO97+jiL71w5e3f5ngKSxptBMOZalYFutUuYO4hJ1eEYwZA6dGy+Z1U9mxWGu3FqkvkmX/juICZVh3cEQ6g+5XP+/ALJu1M+e91v32zf4Yk14Q5iUoUYBEOoX1M+d2ydYd8v38bU5MSlY+vWTrDvl25z1pBUIXYNDaF2Uz57yf0EJHlHMIQ62QtYknrFO4IhsXRweGrtBBNXxWVTOxvtBSxJvWAQDIHl9YBef3ORiTXB1OQEP1pYdC9gSaUyCIZAo8HhxYvJde+5mucfvntArZJUFY4RDIF+Dg5L0nIGwRBwcFjSINk1NADLVw3fefM0Xz46f1n3kIPDkvrFIOiBlZSDaLRRzJePzvOLPzvDsy+d60lJCUlaCYNglVa6A1izVcNffO57vJNpCEjqO4OgQ82u+luVg2j0Zd5sAPhi1tYMuJWkpH5zsLgDrYrArXTGTycDwG4lKamfDIIOtLrqX+mMn0YbxTTi1FFJ/WIQdKDVVX+rHcAaWb5RzJq4sgw0OHVUUv84RtCBZhu43Dg1eakffyWbyCyt+Ll8sBmcOiqpvwyCDuzZvrnll/VqSjl3EySS1EulBUFEXAv8FfCe4u88lpkPR8T1wJeAjcAJYGdmvl5WO3qh7C9r9wSQNEiRme3f1c0vjgjgusz8cURMAH8NPAjcD7yWmY9GxF5gXWb+RqvfNTs7m3Nzc6W0U5LGVUQczczZdu8rbbA4a35cPJ0o/kvgPuBAcfwAsKOsNkiS2it11lBErImI54GzwOHMfA5Yn5mnirecBtY3+ezuiJiLiLlz586V2UxJqrRSgyAzL2bmFuAm4KMRccuy15PaXUKjz+7PzNnMnJ2eni6zmZJUaX1ZR5CZ54FngXuAMxFxA0Dx82w/2iBJaqy0IIiI6YiYKh5PAj8HvAQ8Bewq3rYLeLKsNkiS2itzHcENwIGIWEMtcA5m5lci4n8BByPiAeAksLPENkiS2igtCDLz/wBbGxx/FdhW1t+VJK2MtYYkqeIMAkmqOINAkirOIJCkijMIJKniDAJJqjiDQJIqziCQpIozCCSp4gwCSao4g0CSKq5Sm9cfOjbvJvGStExlguDQsXkeevwFFhYvAjB/foGHHn8BwDCQVGljGwTLr/7feOvCpRCoW1i8yL6njxsEkiptLIOg0dV/Mz9o8ZokVcFYDhbve/r4FVf/zdw4NVlyayRpuI1lEHR6lT85sYY92zeX3BpJGm5jGQTNrvLXrZ1gZmqSAGamJnnk/lsdH5BUeWM5RrBn++bLxgigdvX/8C98xC9+SVpmLIOg/mXvmgFJam8sgwBqYeAXvyS1N5ZjBJKkzpUWBBHxUxHxbET8TUR8JyIeLI5fHxGHI+Ll4ue6stogSWqvzDuCC8C/zcwPAx8D/lVEfBjYCxzJzE3AkeK5JGlASguCzDyVmd8sHv898CIwA9wHHCjedgDYUVYbJEnt9WWMICI2AluB54D1mXmqeOk0sL4fbZAkNVb6rKGIeC/wZeDfZOb/i4hLr2VmRkQ2+dxuYHfx9McRcbzJn/gA8MMeNnnUeP6ef5XPH/w3aHX+/6CTXxCZDb+HeyIiJoCvAE9n5n8ujh0H7sjMUxFxA/C1zOy6zkNEzGXmbG9aPHo8f8+/yucP/hv04vzLnDUUwB8CL9ZDoPAUsKt4vAt4sqw2SJLaK7Nr6HbgV4EXIuL54thvAo8CByPiAeAksLPENkiS2igtCDLzr4Fo8vK2Hv6p/T38XaPI86+2qp8/+G+w6vMvdYxAkjT8LDEhSRU30kEQEfdExPGI+NuIGPsVyhHxhYg4GxHfXnKsMiU7ql62JCKujYj/HRHfKs7/PxTHK3H+dRGxJiKORcRXiueVOf+IOBERL0TE8xExVxxb9fmPbBBExBrgvwCfBD4M/EpRwmKc/XfgnmXHqlSyo+plS94C7srM24AtwD0R8TGqc/51D1KrVFBXtfO/MzO3LJkyuurzH9kgAD4K/G1mfjcz3wb+lFr5irGVmX8FvLbscGVKdlS9bEnW/Lh4OlH8l1Tk/AEi4ibg54HPLzlcmfNvYtXnP8pBMAN8b8nz7xfHqqaSJTuqWrak6BZ5HjgLHM7MSp0/8HvA54B3lhyr0vkn8JcRcbSovgA9OP+x3ZimilqV7Bgn3ZYtGQeZeRHYEhFTwBMRccuy18f2/CPiXuBsZh6NiDsavWecz7/w8cycj4ifBA5HxEtLX+z2/Ef5jmAe+Kklz28qjlXNmaJUB8XPswNuT6mKsiVfBv44Mx8vDlfq3wAgM88Dz1IbM6rK+d8OfCoiTlDrCr4rIv6I6pw/mTlf/DwLPEGti3zV5z/KQfANYFNEfDAirgE+Ta18RdVUpmRH1cuWRMR0cSdAREwCPwe8REXOPzMfysybMnMjtf/fn8nMz1CR84+I6yLiJ+qPgbuBb9OD8x/pBWUR8c+o9RmuAb6Qmb8z4CaVKiK+CNxBrdrgGeBh4BBwENhAUbIjM5cPKI+FiPg48D+BF3i3j/g3qY0TjP2/QUT8Q2qDgWuoXcQdzMz/GBHvpwLnv1TRNfTvMvPeqpx/RHyI2l0A1Lr1/yQzf6cX5z/SQSBJWr1R7hqSJPWAQSBJFWcQSFLFGQSSVHEGgSRVnEEgrVBRBfXvIuL64vm64vnGwbZM6o5BIK1QZn4P+ANq265S/NyfmScG1ihpFVxHIHWhKHVxFPgC8GvAlsxcHGyrpO5YdE7qQmYuRsQe4KvA3YaARpldQ1L3PgmcAm5p90ZpmBkEUhciYgu1om8fA369Xv1RGkUGgbRCRRXUP6C2H8IrwD7gdwfbKql7BoG0cr8GvJKZh4vn/xX4mYj4pwNsk9Q1Zw1JUsV5RyBJFWcQSFLFGQSSVHEGgSRVnEEgSRVnEEhSxRkEklRxBoEkVdz/ByyxmCTHhhhMAAAAAElFTkSuQmCC\n",
      "text/plain": [
       "<matplotlib.figure.Figure at 0x7f45cc194e10>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "plt.scatter(inp, out)\n",
    "plt.xlabel(\"X\")\n",
    "plt.ylabel(\"y\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 54,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 1702
    },
    "colab_type": "code",
    "id": "tfJktUdJ1TSg",
    "outputId": "466ec3bc-af0f-4399-dbf2-eac316f53376"
   },
   "outputs": [
    {
     "ename": "ValueError",
     "evalue": "Variable weight already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:\n\n  File \"<ipython-input-18-3656b024b7ee>\", line 4, in <module>\n    W = tf.get_variable(dtype = tf.float32, name = \"weight\", shape = [1], initializer = tf.initializers.random_normal)\n  File \"/home/vaibagga/.conda/envs/tensorflow/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 2961, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n  File \"/home/vaibagga/.conda/envs/tensorflow/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 2901, in run_ast_nodes\n    if self.run_code(code, result):\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-54-3656b024b7ee>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0my\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mplaceholder\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdtype\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfloat32\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mshape\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0;32mNone\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m1\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0mweights\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m{\u001b[0m\u001b[0;34m}\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 4\u001b[0;31m \u001b[0mW\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_variable\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdtype\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfloat32\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mname\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m\"weight\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mshape\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0minitializer\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0minitializers\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrandom_normal\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      5\u001b[0m \u001b[0mb\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_variable\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdtype\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfloat32\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mname\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m\"bias\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mshape\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0minitializer\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0minitializers\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrandom_normal\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py\u001b[0m in \u001b[0;36mget_variable\u001b[0;34m(name, shape, dtype, initializer, regularizer, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter, constraint, synchronization, aggregation)\u001b[0m\n\u001b[1;32m   1465\u001b[0m       \u001b[0mname\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1466\u001b[0m       \u001b[0mshape\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mshape\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1467\u001b[0;31m       \u001b[0mdtype\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mdtype\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1468\u001b[0m       \u001b[0minitializer\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0minitializer\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1469\u001b[0m       \u001b[0mregularizer\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mregularizer\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py\u001b[0m in \u001b[0;36mget_variable\u001b[0;34m(self, var_store, name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter, constraint, synchronization, aggregation)\u001b[0m\n\u001b[1;32m   1215\u001b[0m           \u001b[0mvalidate_shape\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mvalidate_shape\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1216\u001b[0m           \u001b[0muse_resource\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0muse_resource\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1217\u001b[0;31m           \u001b[0mcustom_getter\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mcustom_getter\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1218\u001b[0m           \u001b[0mconstraint\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mconstraint\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1219\u001b[0m           \u001b[0msynchronization\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0msynchronization\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py\u001b[0m in \u001b[0;36mget_variable\u001b[0;34m(self, name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter, constraint, synchronization, aggregation)\u001b[0m\n\u001b[1;32m    525\u001b[0m       \u001b[0;31m# `fn_args` and `has_kwargs` can handle functions, `functools.partial`,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    526\u001b[0m       \u001b[0;31m# `lambda`.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 527\u001b[0;31m       if (\"constraint\" in function_utils.fn_args(custom_getter) or\n\u001b[0m\u001b[1;32m    528\u001b[0m           function_utils.has_kwargs(custom_getter)):\n\u001b[1;32m    529\u001b[0m         \u001b[0mcustom_getter_kwargs\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"constraint\"\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mconstraint\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py\u001b[0m in \u001b[0;36m_true_getter\u001b[0;34m(name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, constraint, synchronization, aggregation)\u001b[0m\n\u001b[1;32m    479\u001b[0m       \u001b[0;32mif\u001b[0m \u001b[0;34m\"%s/part_0\"\u001b[0m \u001b[0;34m%\u001b[0m \u001b[0mname\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_vars\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    480\u001b[0m         raise ValueError(\n\u001b[0;32m--> 481\u001b[0;31m             \u001b[0;34m\"No partitioner was provided, but a partitioned version of the \"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    482\u001b[0m             \u001b[0;34m\"variable was found: %s/part_0. Perhaps a variable of the same \"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    483\u001b[0m             \"name was already created with partitioning?\" % name)\n",
      "\u001b[0;32m~/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py\u001b[0m in \u001b[0;36m_get_single_variable\u001b[0;34m(self, name, shape, dtype, initializer, regularizer, partition_info, reuse, trainable, collections, caching_device, validate_shape, use_resource, constraint, synchronization, aggregation)\u001b[0m\n\u001b[1;32m    846\u001b[0m         \u001b[0mtb\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0mx\u001b[0m \u001b[0;32mfor\u001b[0m \u001b[0mx\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mtb\u001b[0m \u001b[0;32mif\u001b[0m \u001b[0;34m\"tensorflow/python\"\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mx\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;36m3\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    847\u001b[0m         raise ValueError(\"%s Originally defined at:\\n\\n%s\" % (err_msg, \"\".join(\n\u001b[0;32m--> 848\u001b[0;31m             traceback.format_list(tb))))\n\u001b[0m\u001b[1;32m    849\u001b[0m       \u001b[0mfound_var\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_vars\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    850\u001b[0m       \u001b[0;32mif\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mshape\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mis_compatible_with\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfound_var\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_shape\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mValueError\u001b[0m: Variable weight already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:\n\n  File \"<ipython-input-18-3656b024b7ee>\", line 4, in <module>\n    W = tf.get_variable(dtype = tf.float32, name = \"weight\", shape = [1], initializer = tf.initializers.random_normal)\n  File \"/home/vaibagga/.conda/envs/tensorflow/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 2961, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n  File \"/home/vaibagga/.conda/envs/tensorflow/lib/python3.5/site-packages/IPython/core/interactiveshell.py\", line 2901, in run_ast_nodes\n    if self.run_code(code, result):\n"
     ]
    }
   ],
   "source": [
    "X = tf.placeholder(dtype = tf.float32, shape = [None, 1])\n",
    "y = tf.placeholder(dtype = tf.float32, shape = [None, 1])\n",
    "weights = {}\n",
    "W = tf.get_variable(dtype = tf.float32, name = \"weight\", shape = [1], initializer = tf.initializers.random_normal)\n",
    "b = tf.get_variable(dtype = tf.float32, name = \"bias\", shape = [1], initializer = tf.initializers.random_normal)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {
    "colab": {},
    "colab_type": "code",
    "id": "PoRsXnuO1lVX"
   },
   "outputs": [],
   "source": [
    "def getPrediction(W, X, b):\n",
    "    return W*X + b"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [],
   "source": [
    "def loss(X, y):\n",
    "    return tf.losses.mean_squared_error(getPrediction(X), y)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [],
   "source": [
    "cost = tf.losses.mean_squared_error(W*X + b, y)\n",
    "optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)\n",
    "init = tf.global_variables_initializer()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "The value of a feed cannot be a tf.Tensor object. Acceptable feed values include Python scalars, strings, lists, numpy ndarrays, or TensorHandles.For reference, the tensor object was Tensor(\"Placeholder_7:0\", shape=(?, 1), dtype=float32) which was passed to the feed with key Tensor(\"Placeholder_7:0\", shape=(?, 1), dtype=float32).",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-48-79aa68aebe0b>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      2\u001b[0m     \u001b[0msess\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrun\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0minit\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m     \u001b[0;32mfor\u001b[0m \u001b[0mnum_iter\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mrange\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m100\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 4\u001b[0;31m         \u001b[0msess\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrun\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0moptimizer\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfeed_dict\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m{\u001b[0m\u001b[0mX\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mx\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0my\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0my\u001b[0m\u001b[0;34m}\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      5\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mnum_iter\u001b[0m \u001b[0;34m%\u001b[0m \u001b[0;36m10\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      6\u001b[0m             \u001b[0mcost\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0msess\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrun\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcost\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfeed_dict\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m{\u001b[0m\u001b[0mX\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mx\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0my\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0my\u001b[0m\u001b[0;34m}\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36mrun\u001b[0;34m(self, fetches, feed_dict, options, run_metadata)\u001b[0m\n\u001b[1;32m    875\u001b[0m       \u001b[0mvalue\u001b[0m \u001b[0mmay\u001b[0m \u001b[0mbe\u001b[0m \u001b[0ma\u001b[0m \u001b[0mPython\u001b[0m \u001b[0mscalar\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mstring\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlist\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;32mor\u001b[0m \u001b[0mnumpy\u001b[0m \u001b[0mndarray\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    876\u001b[0m       \u001b[0mthat\u001b[0m \u001b[0mcan\u001b[0m \u001b[0mbe\u001b[0m \u001b[0mconverted\u001b[0m \u001b[0mto\u001b[0m \u001b[0mthe\u001b[0m \u001b[0msame\u001b[0m\u001b[0;31m \u001b[0m\u001b[0;31m`\u001b[0m\u001b[0mdtype\u001b[0m\u001b[0;31m`\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mthat\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 877\u001b[0;31m       \u001b[0mtensor\u001b[0m\u001b[0;34m.\u001b[0m \u001b[0mAdditionally\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;32mif\u001b[0m \u001b[0mthe\u001b[0m \u001b[0mkey\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0ma\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    878\u001b[0m       \u001b[0;31m`\u001b[0m\u001b[0mtf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mplaceholder\u001b[0m\u001b[0;31m`\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mthe\u001b[0m \u001b[0mshape\u001b[0m \u001b[0mof\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    879\u001b[0m       \u001b[0mthe\u001b[0m \u001b[0mvalue\u001b[0m \u001b[0mwill\u001b[0m \u001b[0mbe\u001b[0m \u001b[0mchecked\u001b[0m \u001b[0;32mfor\u001b[0m \u001b[0mcompatibility\u001b[0m \u001b[0;32mwith\u001b[0m \u001b[0mthe\u001b[0m \u001b[0mplaceholder\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36m_run\u001b[0;34m(self, handle, fetches, feed_dict, options, run_metadata)\u001b[0m\n\u001b[1;32m   1049\u001b[0m     \u001b[0;31m# Set up a graph with feeds and fetches for partial run.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1050\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m_setup_fn\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msession\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfeed_list\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfetch_list\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtarget_list\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1051\u001b[0;31m       \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_extend_graph\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1052\u001b[0m       return tf_session.TF_SessionPRunSetup_wrapper(\n\u001b[1;32m   1053\u001b[0m           session, feed_list, fetch_list, target_list)\n",
      "\u001b[0;31mTypeError\u001b[0m: The value of a feed cannot be a tf.Tensor object. Acceptable feed values include Python scalars, strings, lists, numpy ndarrays, or TensorHandles.For reference, the tensor object was Tensor(\"Placeholder_7:0\", shape=(?, 1), dtype=float32) which was passed to the feed with key Tensor(\"Placeholder_7:0\", shape=(?, 1), dtype=float32)."
     ]
    }
   ],
   "source": [
    "with tf.Session() as sess:\n",
    "    sess.run(init)\n",
    "    for num_iter in range(100):\n",
    "        sess.run(optimizer, feed_dict = {X: x, y: y})\n",
    "        if num_iter % 10 == 0:\n",
    "            cost = sess.run(cost, feed_dict = {X: x, y: y})\n",
    "            print(cost)\n",
    "        \n",
    "        \n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "accelerator": "GPU",
  "colab": {
   "collapsed_sections": [],
   "include_colab_link": true,
   "name": "TensorflowCSIR.ipynb",
   "provenance": [],
   "version": "0.3.2"
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1
}
